### ISSUE TITLE
Update appveyor script to ignore non-source changes

### ISSUE THREAD

**Issue by MV10** [serilog/serilog-settings-configuration#130]
Must be changed in `master` branch which I can't do (I don't think). This will skip NuGet package deployments for changes to things like README or unit tests. Based on another of my repos, the change should look something like this:

```yml
only_commits:
  files:
    - Serilog.Settings.Configuration.sln
    - src/Serilog.Settings.Configuration/
```

Should changes to the `assets` folder also trigger a package release?
